---
- hosts: lxc_dev_cluster
  vars:
    jenkins_helm_values:
      controller:
        jenkinsUriPrefix: "/jenkins"
        ingress:
          enabled: true
          hostName: "anpham.me"
          path: "/jenkins"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            kubernetes.io/ingress.class: "nginx"
          tls:
            - secretName: jenkins-tls
              hosts:
                - anpham.me
  roles:
    - jenkins-helm